[package]
name = "in_form"
version = "0.0.1-alpha"
edition = "2024"
description = "Define a type and get your data from a GUI without writing one."
license = "MIT"
readme = "README.md"
repository = "https://github.com/Jsjjjs6066/in-form"
keywords = ["form", "ui", "input"]
categories = ["development-tools"]
authors = ["Leon Žlender"]

[dependencies]
in_form_derive = { path = "in_form_derive", version = "0.0.1-alpha" }
