[package]
name = "in_form_derive"
version = "0.1.0-alpha"
edition = "2024"
description = "Derive macro for `in_form::Renderer` trait."
license = "MIT"
repository = "https://github.com/Jsjjjs6066/in-form"
keywords = ["form", "ui", "input"]
categories = ["development-tools"]
authors = ["Leon Žlender"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = { version = "3.0.3", features = ["extra-traits"] }
